interface Developer {
  value: string;
  displayName: string;
}

export const developers: Developer[] = [
  // Most common developers
  { value: "D-76", displayName: "Kodak D-76" },
  { value: "HC-110%", displayName: "Kodak HC-110" },
  { value: "Xtol%", displayName: "Kodak Xtol" },
  { value: "Rodinal", displayName: "Rodinal" },
  { value: "ID-11%", displayName: "Ilford ID-11" },
  { value: "Ilfosol 3%", displayName: "Ilford Ilfosol 3" },
  { value: "Microphen%", displayName: "Ilford Microphen" },
  { value: "Perceptol%", displayName: "Ilford Perceptol" },

  // All other developers
  { value: "123-Pyro%", displayName: "123-Pyro" },
  { value: "510-Pyro%", displayName: "510-Pyro" },
  { value: "777%", displayName: "777" },
  { value: "Atomal 49%", displayName: "A49" },
  { value: "A&B Lith%", displayName: "A&B Lith" },
  { value: "ABC Pyro%", displayName: "ABC Pyro" },
  { value: "ACU-1%", displayName: "ACU-1" },
  { value: "Acufine%", displayName: "Acufine" },
  { value: "Acurol-N%", displayName: "Acurol-N" },
  { value: "Adotech III%", displayName: "Adotech III" },
  { value: "ADX II%", displayName: "ADX II" },
  { value: "Agfa 12%", displayName: "Agfa 12" },
  { value: "Agfa 14%", displayName: "Agfa 14" },
  { value: "Agfa Ansco 47%", displayName: "Agfa Ansco 47" },
  { value: "Amaloco AM74%", displayName: "AM74" },
  { value: "Arista%", displayName: "Arista developers" },
  { value: "Ars-Imago%", displayName: "Ars-Imago developers" },
  { value: "Atomal 49%", displayName: "Atomal 49" },
  { value: "Ber%", displayName: "Bergger developers" },
  { value: "Beutler%", displayName: "Beutler" },
  { value: "Black/White & Green", displayName: "Black/White & Green" },
  { value: "Bluefire HR%", displayName: "Bluefire HR" },
  { value: "Burton 195%", displayName: "Burton 195" },
  { value: "BW-TNEG%", displayName: "BW-TNEG" },
  { value: "C-41%", displayName: "C-41" },
  { value: "Caffenol%", displayName: "Caffenol developers" },
  { value: "Cawanol%", displayName: "Cawanol" },
  { value: "D-9", displayName: "D-9" },
  { value: "D-11", displayName: "D-11" },
  { value: "D-19", displayName: "D-19" },
  { value: "D-23", displayName: "D-23" },
  { value: "D-25", displayName: "D-25" },
  { value: "D-72", displayName: "D-72" },
  { value: "D-96", displayName: "D-96" },
  { value: "Dektol%", displayName: "Dektol" },
  { value: "Bellini DF2 Duo Step", displayName: "DF2 Duo Step" },
  { value: "Diafine%", displayName: "Diafine" },
  { value: "DiXactol Ultra%", displayName: "DiXactol Ultra" },
  { value: "DK-50", displayName: "DK-50" },
  { value: "DK-76", displayName: "DK-76" },
  { value: "DK-76b", displayName: "DK-76b" },
  { value: "Dokumol%", displayName: "Dokumol" },
  { value: "DS-10%", displayName: "DS-10" },
  { value: "Ecofilm", displayName: "Ecofilm" },
  { value: "Ecoprint Universal%", displayName: "Ecoprint Universal" },
  { value: "Eco Pro%", displayName: "Eco Pro Film Dev" },
  { value: "Emofin%", displayName: "Emofin" },
  { value: "Eukobrom%", displayName: "Eukobrom" },
  { value: "EXG1%", displayName: "EXG1" },
  { value: "Extend Plus%", displayName: "Extend Plus" },
  { value: "F76+%", displayName: "F76+" },
  { value: "FA-1027%", displayName: "FA-1027" },
  { value: "FD10%", displayName: "FD10" },
  { value: "Finol%", displayName: "Finol" },
  { value: "Foma%", displayName: "Foma developers" },
  { value: "FX-1", displayName: "FX-1" },
  { value: "FX-2", displayName: "FX-2" },
  { value: "FX-4", displayName: "FX-4" },
  { value: "FX-5", displayName: "FX-5" },
  { value: "Bellini FX6a%", displayName: "FX6a Monobath" },
  { value: "FX-15", displayName: "FX-15" },
  { value: "FX-19", displayName: "FX-19" },
  { value: "FX-37", displayName: "FX-37" },
  { value: "FX-39", displayName: "FX-39" },
  { value: "FX-55", displayName: "FX-55" },
  { value: "Ornano Gradual ST20%", displayName: "Gradual ST20" },
  { value: "GSD-10%", displayName: "GSD-10" },
  { value: "Adox HR-DEV%", displayName: "HR-DEV" },
  { value: "Hubl Glycin Paste%", displayName: "Hubl Glycin Paste" },
  { value: "Hypercat%", displayName: "Hypercat" },
  { value: "Bellini Hydrofen", displayName: "Hydrofen" },
  { value: "ID-62%", displayName: "ID-62" },
  { value: "ID-68%", displayName: "ID-68" },
  { value: "Ilfotec DD%", displayName: "Ilfotec DD/DD-X" },
  { value: "Ilfotec HC%", displayName: "Ilfotec HC" },
  { value: "Ilfotec LC29%", displayName: "Ilfotec LC29" },
  { value: "Ilfotec RT Rapid%", displayName: "Ilfotec RT Rapid" },
  { value: "Kalogen%", displayName: "Kalogen" },
  { value: "Liquidol%", displayName: "Liquidol" },
  { value: "Marathon", displayName: "Marathon" },
  { value: "Melonal%", displayName: "Melonal" },
  { value: "Meritol-Metol%", displayName: "Meritol-Metol" },
  { value: "Metolal%", displayName: "Metolal" },
  { value: "Microdol-X%", displayName: "Microdol-X" },
  { value: "Fuji Microfine", displayName: "Microfine" },
  { value: "Mocon%", displayName: "Mocon" },
  { value: "Moersch eco%", displayName: "Moersch eco" },
  { value: "MZB%", displayName: "MZB" },
  { value: "Neofin Blue%", displayName: "Neofin Blue" },
  { value: "Neopress HC%", displayName: "Neopress HC" },
  { value: "Neutol%", displayName: "Neutol" },
  { value: "Nucleol BF200%", displayName: "Nucleol BF200" },
  { value: "Obsidian Aqua%", displayName: "Obsidian Aqua" },
  { value: "Paranol S%", displayName: "Paranol S" },
  { value: "Parodinal%", displayName: "Parodinal" },
  { value: "Parvofin", displayName: "Parvofin" },
  { value: "PC-TEA%", displayName: "PC-TEA" },
  { value: "PCK%", displayName: "PCK" },
  { value: "PMK%", displayName: "PMK" },
  { value: "POTA%", displayName: "POTA" },
  { value: "PQ Universal%", displayName: "PQ Universal" },
  { value: "Prescysol%", displayName: "Prescysol" },
  { value: "Promicrol%", displayName: "Promicrol" },
  { value: "Pyrocat%", displayName: "Pyrocat" },
  { value: "R09", displayName: "R09" },
  { value: "RodinalSpecial", displayName: "Rodinal Special" },
  { value: "Rollei%", displayName: "Rollei developers" },
  { value: "Rollo Pyro%", displayName: "Rollo Pyro" },
  { value: "Romek%", displayName: "Romek developers" },
  { value: "Silberra%", displayName: "Silberra developers" },
  { value: "Silvermax%", displayName: "Silvermax" },
  { value: "SP-76EC%", displayName: "SP-76EC" },
  { value: "SPD%", displayName: "SPD" },
  { value: "Sprint Standard%", displayName: "Sprint Standard" },
  { value: "Spur%", displayName: "Spur developers" },
  { value: "Stoeckler%", displayName: "Stoeckler" },
  { value: "Studional%", displayName: "Studional" },
  { value: "Suprol%", displayName: "Suprol" },
  { value: "Tanol%", displayName: "Tanol" },
  { value: "TD-3%", displayName: "TD-3" },
  { value: "TFX-2%", displayName: "TFX-2" },
  { value: "TMax Dev%", displayName: "TMax Dev" },
  { value: "TMax RS%", displayName: "TMax RS" },
  { value: "Ultrafin", displayName: "Ultrafin" },
  { value: "Ultrafin T-Plus%", displayName: "Ultrafin T-Plus" },
  { value: "Ultrafine%", displayName: "Ultrafine developers" },
  { value: "Uncle%", displayName: "Uncle Mort's" },
  { value: "WD2D+%", displayName: "WD2D+" },
  { value: "Windisch%", displayName: "Windisch" },
  { value: "XT-3", displayName: "XT-3" }
]; 